### ISSUE TITLE
IMPRS Proposal Brainstorm

### ISSUE THREAD

**Issue by jfy133** [TCLamnidis/BareBonesBash#2]
- What about windows laptops? Run everything with GWDG cluster instance
- Have 30m into presentation 'wtf is unix/terminal'?
- Survey at end of tutorial to see what people are feeling comfortable with. Things that are problematic can review
- Hour discussion to see what sort of files people normally deal with, and how Bash can help them

**Comment by aidaanva** [comment]
-  usage of grep (for ex. no need to cat the file before using it)

- loops: for, while (more examples of how they exactly work and how to set them up)

- strings substitutions with for example sed or tr

- Arrays: what they are and how they work

**Comment by TCLamnidis** [comment]
I think the presentation should not be a whole 30min, but rather a modular bit where we run through a few slides per section.
