### ISSUE TITLE
IMPRS - Basic BBB 2019 Presentation(s) Brain storm

### ISSUE THREAD

**Issue by jfy133** [TCLamnidis/BareBonesBash#3]
# Intro

- [x]  Who are we?
- [x]  We know nothing, but Google does.
- [x]  Aims
  - Not for you to be a coder/programmer
  - Familiarise you with how command works/looks/feels
  - Identify when CLI could be useful
- [x]  Most important - DOCUMENT EVERYTHING YOU DO (saves your butt)

# Post content
Live problem-solving of examples of problems from attendees?
Translation for windows users?

Homework: show written example of applying your knowledge (and google-fu) to solve an issue but with command line (DOCUMENTATION!). Doesn't have to work!

**Comment by jfy133** [comment]
Post Presentation (still un-fixed) notes - prior to release!

- Explain what bash is
- Why a tilde, when I can just use the name (when it is already in the directory)
- People don't make the `bosh` typo (come up with a different funny reason to move to rename)
- `rm` the files starting with F (the little middle session test) doesn't work because people didn't understand the waiting for input prompt '>', which wasn't displayed in the presentation

Organisation
- >3hr sessions can get coffee/biscuits! Ask for it next time!

**Comment by TCLamnidis** [comment]
- Added explanation of bash
- Left tilde in, cause it is a teachable moment, that both relative and absolute paths work.
- changed `bosh` typo. dir now named `BBB`.
- Added `>` prompt in all for loops

**Comment by jfy133** [comment]
Also add: for for loops, add example of echoing the command itself (with the variable) to show this is actually what the computer is doing.

**Comment by jfy133** [comment]
Transferred everything over to main walkthrough: https://github.com/TCLamnidis/BareBonesBash/commit/82149452c71e6f627ea1822c305b521eed2efecb

We leave this open until 19th Dec 2019 and we go through feedback form from this session.
